# full
# [[models]]
# url = "https://huggingface.co/Comfy-Org/HiDream-I1_ComfyUI/resolve/main/split_files/diffusion_models/hidream_i1_full_fp16.safetensors"
# dir = "models/diffusion_models/hidream"
# filename = "hidream_i1_full_bf16.safetensors"
[[models]]
url = "https://huggingface.co/Comfy-Org/HiDream-I1_ComfyUI/resolve/main/split_files/diffusion_models/hidream_i1_full_fp8.safetensors"
dir = "models/diffusion_models/hidream"
filename = "hidream_i1_full_fp8.safetensors"

# # dev
# [[models]]
# url = "https://huggingface.co/Comfy-Org/HiDream-I1_ComfyUI/resolve/main/split_files/diffusion_models/hidream_i1_dev_bf16.safetensors"
# dir = "models/diffusion_models/hidream"
# filename = "hidream_i1_dev_bf16.safetensors"
# [[models]]
# url = "https://huggingface.co/Comfy-Org/HiDream-I1_ComfyUI/resolve/main/split_files/diffusion_models/hidream_i1_dev_fp8.safetensors"
# dir = "models/diffusion_models/hidream"
# filename = "hidream_i1_dev_fp8.safetensors"

# # fast
# [[models]]
# url = "https://huggingface.co/Comfy-Org/HiDream-I1_ComfyUI/resolve/main/split_files/diffusion_models/hidream_i1_fast_bf16.safetensors"
# dir = "models/diffusion_models/hidream"
# filename = "hidream_i1_fast_bf16.safetensors"
# [[models]]
# url = "https://huggingface.co/Comfy-Org/HiDream-I1_ComfyUI/resolve/main/split_files/diffusion_models/hidream_i1_fast_fp8.safetensors"
# dir = "models/diffusion_models/hidream"
# filename = "hidream_i1_fast_fp8.safetensors"
