[[models]]
url = "https://huggingface.co/Comfy-Org/HiDream-I1_ComfyUI/resolve/main/split_files/diffusion_models/hidream_e1_1_bf16.safetensors"
dir = "models/diffusion_models/hidream"
filename = "hidream_e1_1_bf16.safetensors"
