# text_encoders
[[models]]
url = "https://huggingface.co/Comfy-Org/stable-diffusion-3.5-fp8/resolve/main/text_encoders/clip_l.safetensors"
dir = "models/text_encoders"
filename = "clip_l.safetensors"
[[models]]
url = "https://huggingface.co/zer0int/CLIP-GmP-ViT-L-14/resolve/main/ViT-L-14-BEST-smooth-GmP-TE-only-HF-format.safetensors"
dir = "models/text_encoders"
filename = "ViT-L-14-BEST-smooth-GmP-TE-only-HF-format.safetensors"
[[models]]
url = "https://huggingface.co/zer0int/CLIP-GmP-ViT-L-14/resolve/main/ViT-L-14-TEXT-detail-improved-hiT-GmP-TE-only-HF.safetensors"
dir = "models/text_encoders"
filename = "ViT-L-14-TEXT-detail-improved-hiT-GmP-TE-only-HF.safetensors"

[[models]]
url = "https://huggingface.co/Comfy-Org/stable-diffusion-3.5-fp8/resolve/main/text_encoders/clip_g.safetensors"
dir = "models/text_encoders"
filename = "clip_g.safetensors"

[[models]]
url = "https://huggingface.co/Comfy-Org/stable-diffusion-3.5-fp8/resolve/main/text_encoders/t5xxl_fp16.safetensors"
dir = "models/text_encoders"
filename = "t5xxl_fp16.safetensors"

[[models]]
url = "https://huggingface.co/Comfy-Org/stable-diffusion-3.5-fp8/resolve/main/text_encoders/t5xxl_fp8_e4m3fn_scaled.safetensors"
dir = "models/text_encoders"
filename = "t5xxl_fp8_e4m3fn_scaled.safetensors"

[[models]]
url = "https://huggingface.co/city96/t5-v1_1-xxl-encoder-gguf/resolve/main/t5-v1_1-xxl-encoder-Q8_0.gguf"
dir = "models/text_encoders"
filename = "t5-v1_1-xxl-encoder-Q8_0.gguf"
