# fp8
[[models]]
url = "https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI/resolve/main/split_files/diffusion_models/qwen_image_fp8_e4m3fn.safetensors"
dir = "models/diffusion_models/qwen-image"
filename = "qwen_image_fp8_e4m3fn.safetensors"

[[models]]
url = "https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI/resolve/main/split_files/vae/qwen_image_vae.safetensors"
dir = "models/vae"
filename = "qwen_image_vae.safetensors"

[[models]]
url = "https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI/resolve/main/split_files/text_encoders/qwen_2.5_vl_7b_fp8_scaled.safetensors"
dir = "models/text_encoders"
filename = "qwen_2.5_vl_7b_fp8_scaled.safetensors"
