[[models]]
url = "https://huggingface.co/nunchaku-tech/nunchaku-qwen-image/resolve/main/svdq-fp4_r128-qwen-image.safetensors"
dir = "models/diffusion_models/qwen-image"
filename = "svdq-fp4_r128-qwen-image.safetensors"

[[models]]
url = "https://www.modelscope.cn/models/nunchaku-tech/nunchaku-qwen-image/resolve/master/svdq-fp4_r128-qwen-image-lightningv1.1-8steps.safetensors"
dir = "models/diffusion_models/qwen-image"
filename = "svdq-fp4_r128-qwen-image-lightningv1.1-8steps.safetensors"
