# fp8_e4m3fn
# aio, all 2 text encoders & vae baked in
[[models]]
url = "https://huggingface.co/Comfy-Org/flux1-dev/blob/main/flux1-dev-fp8.safetensors"
dir = "models/checkpoints/flux1"
filename = "flux1-dev-fp8-e4m3fn.safetensors"

# [[models]]
# url = "https://huggingface.co/Comfy-Org/flux1-schnell/blob/main/flux1-schnell-fp8.safetensors"
# dir = "models/checkpoints/flux1"
# filename = "flux1-schnell-fp8-e4m3fn.safetensors"