# origin
[[models]]
url = "https://huggingface.co/black-forest-labs/FLUX.1-Fill-dev/blob/main/flux1-fill-dev.safetensors"
dir = "models/diffusion_models/flux1"
filename = "flux1-fill-dev.safetensors"

[[models]]
url = "https://huggingface.co/black-forest-labs/FLUX.1-Redux-dev/blob/main/flux1-redux-dev.safetensors"
dir = "models/style_models/flux1"
filename = "flux1-redux-dev.safetensors"
[[models]]
url = "https://huggingface.co/Comfy-Org/sigclip_vision_384/blob/main/sigclip_vision_patch14_384.safetensors"
dir = "models/clip_vision"
filename = "sigclip_vision_patch14_384.safetensors"