# VAE
[[models]]
url = "https://huggingface.co/black-forest-labs/FLUX.1-dev/blob/main/ae.safetensors"
dir = "models/vae/flux1"
filename = "ae.safetensors"

# TAEF1 Decoder
[[models]]
url = "https://github.com/madebyollin/taesd/blob/main/taef1_decoder.pth"
dir = "models/vae_approx"
filename = "taef1_decoder.pth"

# TAEF1 Encoder
[[models]]
url = "https://github.com/madebyollin/taesd/raw/refs/heads/main/taef1_encoder.pth"
dir = "models/vae_approx"
filename = "taef1_encoder.pth"