[[models]]
url = "https://huggingface.co/black-forest-labs/FLUX.1-Canny-dev-lora/resolve/main/flux1-canny-dev-lora.safetensors"
dir = "models/loras/flux1"
filename = "flux1-canny-dev-lora.safetensors"

[[models]]
url = "https://huggingface.co/black-forest-labs/FLUX.1-Depth-dev-lora/resolve/main/flux1-depth-dev-lora.safetensors"
dir = "models/loras/flux1"
filename = "flux1-depth-dev-lora.safetensors"
