# origin
[[models]]
url = "https://huggingface.co/black-forest-labs/FLUX.1-dev/blob/main/flux1-dev.safetensors"
dir = "models/diffusion_models/flux1"
filename = "flux1-dev.safetensors"

# [[models]]
# url = "https://huggingface.co/black-forest-labs/FLUX.1-schnell/blob/main/flux1-schnell.safetensors"
# dir = "models/diffusion_models/flux1"
# filename = "flux1-schnell.safetensors"
