# origin
# [[models]]
# url = "https://huggingface.co/black-forest-labs/FLUX.1-dev/resolve/main/flux1-dev.safetensors"
# dir = "models/diffusion_models/flux1"
# filename = "flux1-dev.safetensors"

# [[models]]
# url = "https://huggingface.co/black-forest-labs/FLUX.1-schnell/resolve/main/flux1-schnell.safetensors"
# dir = "models/diffusion_models/flux1"
# filename = "flux1-schnell.safetensors"

# fp8_e4m3fn
# aio, all 2 text encoders & vae baked in
[[models]]
url = "https://huggingface.co/Comfy-Org/flux1-dev/resolve/main/flux1-dev-fp8.safetensors"
dir = "models/checkpoints/flux1"
filename = "flux1-dev-fp8-e4m3fn.safetensors"

# [[models]]
# url = "https://huggingface.co/Comfy-Org/flux1-schnell/resolve/main/flux1-schnell-fp8.safetensors"
# dir = "models/checkpoints/flux1"
# filename = "flux1-schnell-fp8-e4m3fn.safetensors"

# flux1-krea-dev
[[models]]
url = "https://huggingface.co/Comfy-Org/FLUX.1-Krea-dev_ComfyUI/resolve/main/split_files/diffusion_models/flux1-krea-dev_fp8_scaled.safetensors"
dir = "models/checkpoints/flux1"
filename = "flux1-krea-dev_fp8_scaled.safetensors"
