# flux1-turbo-alpha lora
[[models]]
url = "https://huggingface.co/alimama-creative/FLUX.1-Turbo-Alpha/resolve/main/diffusion_pytorch_model.safetensors"
dir = "models/loras/flux1"
filename = "flux.1-turbo-alpha.safetensors"

# hypersd
[[models]]
url = "https://huggingface.co/ByteDance/Hyper-SD/resolve/main/Hyper-FLUX.1-dev-8steps-lora.safetensors"
dir = "models/loras/flux1"
filename = "Hyper-FLUX.1-dev-8steps-lora.safetensors"

[[models]]
url = "https://huggingface.co/ByteDance/Hyper-SD/resolve/main/Hyper-FLUX.1-dev-16steps-lora.safetensors"
dir = "models/loras/flux1"
filename = "Hyper-FLUX.1-dev-16steps-lora.safetensors"
