[[models]]
url = "https://huggingface.co/black-forest-labs/FLUX.1-Canny-dev-lora/resolve/main/flux1-canny-dev-lora.safetensors"
dir = "models/loras/flux1"
filename = "flux1-canny-dev-lora.safetensors"

[[models]]
url = "https://huggingface.co/black-forest-labs/FLUX.1-Depth-dev-lora/resolve/main/flux1-depth-dev-lora.safetensors"
dir = "models/loras/flux1"
filename = "flux1-depth-dev-lora.safetensors"

[[models]]
url = "https://huggingface.co/Shakker-Labs/FLUX.1-dev-ControlNet-Union-Pro-2.0/resolve/main/diffusion_pytorch_model.safetensors"
dir = "models/controlnet/flux1"
filename = "flux1-dev-controlnet-union-pro-2.0.safetensors"

[[models]]
url = "https://huggingface.co/alimama-creative/FLUX.1-dev-Controlnet-Inpainting-Beta/resolve/main/diffusion_pytorch_model.safetensors"
dir = "models/controlnet/flux1"
filename = "flux1-dev-controlnet-inpainting-beta.safetensors"
