[[custom_nodes]]
node_id = "ComfyUI-nunchaku"
url = "https://github.com/nunchaku-tech/ComfyUI-nunchaku"
version = "0.3.4"

[[custom_nodes]]
node_id = "teacache"
url = "https://github.com/welltop-cn/ComfyUI-TeaCache"
