# [[custom_nodes]]
# node_id = "comfyui_llm_party"
# url = "https://github.com/heshengtao/comfyui_LLM_party"

[[custom_nodes]]
node_id = "comfyui-ollama"
url = "https://github.com/stavsap/comfyui-ollama"
