[[custom_nodes]]
node_id = "comfyui-videohelpersuite"
url = "https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite"

[[custom_nodes]]
node_id = "comfyui-animatediff-evolved"
url = "https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved"

[[custom_nodes]]
node_id = "comfyui-frame-interpolation"
url = "https://github.com/Fannovel16/ComfyUI-Frame-Interpolation"
