# # example
# [[custom_nodes]]
# url = ""
# post_script = "" ## todo

[[custom_nodes]]
url = "https://github.com/ltdrdata/ComfyUI-Manager"

[[custom_nodes]]
url = "https://github.com/ltdrdata/ComfyUI-Impact-Pack"

[[custom_nodes]]
url = "https://github.com/ltdrdata/ComfyUI-Inspire-Pack"

[[custom_nodes]]
url = "https://github.com/yolain/ComfyUI-Easy-Use"

[[custom_nodes]]
url = "https://github.com/chflame163/ComfyUI_LayerStyle"

[[custom_nodes]]
url = "https://github.com/chflame163/ComfyUI_LayerStyle_Advance"

[[custom_nodes]]
url = "https://github.com/Fannovel16/comfyui_controlnet_aux"

[[custom_nodes]]
url = "https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet"

[[custom_nodes]]
url = "https://github.com/rgthree/rgthree-comfy"

[[custom_nodes]]
url = "https://github.com/kijai/ComfyUI-KJNodes"

[[custom_nodes]]
url = "https://github.com/cubiq/ComfyUI_IPAdapter_plus"

[[custom_nodes]]
url = "https://github.com/crystian/ComfyUI-Crystools"

[[custom_nodes]]
url = "https://github.com/pythongosssss/ComfyUI-Custom-Scripts"

[[custom_nodes]]
url = "https://github.com/pythongosssss/ComfyUI-WD14-Tagger"

[[custom_nodes]]
url = "https://github.com/Acly/comfyui-inpaint-nodes"

[[custom_nodes]]
url = "https://github.com/Trung0246/ComfyUI-0246"

[[custom_nodes]]
url = "https://github.com/filliptm/ComfyUI_Fill-Nodes"

# [[custom_nodes]]
# url = "https://github.com/BennyKok/comfyui-deploy"