services:
  comfyui-docker:
    image: jimlee2048/comfyui-docker:latest
    container_name: comfyui-docker
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8188:8188
    volumes:
      - ./volume/user:/workspace/ComfyUI/user
      - ./volume/output:/workspace/ComfyUI/output
      - ./volume/models:/workspace/ComfyUI/models
      - ../config:/workspace/boot_config
      ## optional: extra model paths
      ## https://github.com/comfyanonymous/ComfyUI/blob/master/extra_model_paths.yaml.example
      # - ./extra_model_paths.yaml:/workspace/ComfyUI/extra_model_paths.yaml
      # - /path/to/sd-webui-a1111/models:/workspace/external_models/sd-webui-a1111
      ## optional: external custom_nodes folder
      # - /path/to/a_custom_nodes:/workspace/ComfyUI/custom_nodes/a_custom_nodes
    security_opt:
      - "label=type:nvidia_container_t"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]