[[models]]
url = "https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/ip-adapter_sdxl_vit-h.safetensors"
dir = "models/ipadapter"
filename = "ip-adapter_sdxl_vit-h.safetensors"

[[models]]
url = "https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/ip-adapter-plus_sdxl_vit-h.safetensors"
dir = "models/ipadapter"
filename = "ip-adapter-plus_sdxl_vit-h.safetensors"

[[models]]
url = "https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/ip-adapter-plus-face_sdxl_vit-h.safetensors"
dir = "models/ipadapter"
filename = "ip-adapter-plus-face_sdxl_vit-h.safetensors"

[[models]]
url = "https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/ip-adapter_sdxl.safetensors"
dir = "models/ipadapter"
filename = "ip-adapter_sdxl.safetensors"

[[models]]
url = "https://huggingface.co/ostris/ip-composition-adapter/resolve/main/ip_plus_composition_sdxl.safetensors"
dir = "models/ipadapter"
filename = "ip_plus_composition_sdxl.safetensors"