# Pony Diffusion V6 XL
[[models]]
url = "https://civitai.com/api/download/models/290640?type=Model&format=SafeTensor&size=pruned&fp=fp16"
dir = "models/checkpoints/sdxl"
filename = "pony-diffusion-v6-xl.safetensors"

# AnimagineXL 4.0
[[models]]
url = "https://huggingface.co/cagliostrolab/animagine-xl-4.0/resolve/main/animagine-xl-4.0-opt.safetensors"
dir = "models/checkpoints/sdxl"
filename = "animagine-xl-4.0-opt.safetensors"

# Kohaku XL Zeta
[[models]]
url = "https://huggingface.co/KBlueLeaf/Kohaku-XL-Zeta/resolve/main/kohaku-xl-zeta.safetensors"
dir = "models/checkpoints/sdxl"
filename = "kohaku-xl-zeta.safetensors"

# NoobAI XL 1.1
[[models]]
url = "https://huggingface.co/Laxhar/noobai-XL-1.1/resolve/main/NoobAI-XL-v1.1.safetensors"
dir = "models/checkpoints/sdxl"
filename = "noobai-XL-1.1.safetensors"

# NoobAI XL Vpred 1.0
[[models]]
url = "https://huggingface.co/Laxhar/noobai-XL-Vpred-1.0/resolve/main/NoobAI-XL-Vpred-v1.0.safetensors"
dir = "models/checkpoints/sdxl"
filename = "noobai-XL-Vpred-1.0.safetensors"

# Nyanko XL Alpha
[[models]]
url = "https://huggingface.co/nyanko7/nyaflow-xl-alpha/resolve/main/model.safetensors"
dir = "models/checkpoints/sdxl"
filename = "nyaflow-xl-alpha.safetensors"
