# ### animaginexl
# [[models.checkpoints.items]]
# category = "sdxl"
# url ="https://huggingface.co/cagliostrolab/animagine-xl-3.1/resolve/main/animagine-xl-3.1.safetensors"

# Pony Diffusion V6 XL
[[models]]
url = "https://civitai.com/api/download/models/290640?type=Model&format=SafeTensor&size=pruned&fp=fp16"
dir = "models/checkpoints/sdxl"
filename = "pony-diffusion-v6-xl.safetensors"

# AnimagineXL 3.1
[[models]]
url = "https://huggingface.co/cagliostrolab/animagine-xl-3.1/resolve/main/animagine-xl-3.1.safetensors"
dir = "models/checkpoints/sdxl"
filename = "animagine-xl-3.1.safetensors"

# Kohaku XL Zeta
[[models]]
url = "https://huggingface.co/KBlueLeaf/Kohaku-XL-Zeta/blob/main/kohaku-xl-zeta.safetensors"
dir = "models/checkpoints/sdxl"
filename = "kohaku-xl-zeta.safetensors"

# NoobAI XL 1.1
[[models]]
url = "https://huggingface.co/Laxhar/noobai-XL-1.1/blob/main/NoobAI-XL-v1.1.safetensors"
dir = "models/checkpoints/sdxl"
filename = "noobai-XL-1.1.safetensors"

# NoobAI XL Vpred 1.0
[[models]]
url = "https://huggingface.co/Laxhar/noobai-XL-Vpred-1.0/blob/main/NoobAI-XL-Vpred-v1.0.safetensors"
dir = "models/checkpoints/sdxl"
filename = "noobai-XL-Vpred-1.0.safetensors"

