name: "Docker Build and Publish"

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push: 
    branches: [ main ]
    paths:
      - 'comfyui/docker/Dockerfile'
      - 'comfyui/docker/boot.py'

jobs:
  fetch-release:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.get-latest-release.outputs.tag }}
      is_new_release: ${{ steps.check-release.outputs.is_new_release }}
    steps:
      - name: Get latest release
        id: get-latest-release
        run: |
          LATEST_TAG=$(curl -sL https://api.github.com/repos/comfyanonymous/ComfyUI/releases/latest | jq -r .tag_name)
          echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Restore cached release tag
        id: cache-release
        uses: actions/cache@v3
        with:
          path: ~/.release-tag
          key: release-tag

      - name: Check if new release
        id: check-release
        run: |
          CACHED_TAG=""
          if [ -f ~/.release-tag ]; then
            CACHED_TAG=$(cat ~/.release-tag)
          fi
          
          if [ "$CACHED_TAG" != "${{ steps.get-latest-release.outputs.tag }}" ]; then
            echo "is_new_release=true" >> $GITHUB_OUTPUT
            echo "${{ steps.get-latest-release.outputs.tag }}" > ~/.release-tag
          else
            echo "is_new_release=false" >> $GITHUB_OUTPUT
          fi

  build-and-push:
    needs: fetch-release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image_tag: nightly
            comfyui_version: master
          - image_tag: latest
            comfyui_version: ${{ needs.fetch-release.outputs.release_tag }}
    if: |
      github.job.matrix.image_tag == 'nightly' || 
      (github.job.matrix.image_tag == 'latest' && needs.fetch-release.outputs.is_new_release == 'true')
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_USERNAME }}/comfyui-docker
          tags: |
            type=raw,value=${{ matrix.image_tag }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./comfyui/docker
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            COMFYUI_VERSION=${{ matrix.comfyui_version }}