# official-vace
[[models]]
url = "https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/diffusion_models/wan2.1_vace_1.3B_fp16.safetensors"
dir = "models/diffusion_models/wan21"
filename = "wan2.1_vace_1.3B_fp16.safetensors"

[[models]]
url = "https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/diffusion_models/wan2.1_vace_14B_fp16.safetensors"
dir = "models/diffusion_models/wan21"
filename = "wan2.1_vace_14B_fp16.safetensors"

# bytedance-magref
# https://github.com/MAGREF-Video/MAGREF
[[models]]
url = "https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/diffusion_models/wan2.1_magref_14B_fp16.safetensors"
dir = "models/diffusion_models/wan21"
filename = "wan2.1_magref_14B_fp16.safetensors"

# wan 2.1 fun
[[models]]
url = "https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/diffusion_models/wan2.1_fun_inp_1.3B_bf16.safetensors"
dir = "models/diffusion_models/wan21"
filename = "wan2.1_fun_inp_1.3B_bf16.safetensors"

[[models]]
url = "https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/diffusion_models/wan2.1_fun_control_1.3B_bf16.safetensors"
dir = "models/diffusion_models/wan21"
filename = "wan2.1_fun_control_1.3B_bf16.safetensors"

[[models]]
url = "https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/diffusion_models/wan2.1_fun_camera_v1.1_14B_bf16.safetensors"
dir = "models/diffusion_models/wan21"
filename = "wan2.1_fun_camera_v1.1_14B_bf16.safetensors"

[[models]]
url = "https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/diffusion_models/wan2.1_fun_camera_v1.1_1.3B_bf16.safetensors"
dir = "models/diffusion_models/wan21"
filename = "wan2.1_fun_camera_v1.1_1.3B_bf16.safetensors"
