# text encoder
[[models]]
url = "https://huggingface.co/comfyanonymous/cosmos_1.0_text_encoder_and_VAE_ComfyUI/resolve/main/text_encoders/oldt5_xxl_fp8_e4m3fn_scaled.safetensors"
dir = "models/text_encoders"
filename = "oldt5_xxl_fp8_e4m3fn_scaled.safetensors"

# vae
[[models]]
url = "https://huggingface.co/comfyanonymous/cosmos_1.0_text_encoder_and_VAE_ComfyUI/resolve/main/vae/cosmos_cv8x8x8_1.0.safetensors"
dir = "models/vae"
filename = "cosmos_cv8x8x8_1.0.safetensors"

# 7B
[[models]]
url = "https://huggingface.co/mcmonkey/cosmos-1.0/resolve/main/Cosmos-1_0-Diffusion-7B-Video2World.safetensors"
dir = "models/diffusion_models"
filename = "Cosmos-1_0-Diffusion-7B-Video2World.safetensors"

[[models]]
url = "https://huggingface.co/mcmonkey/cosmos-1.0/resolve/main/Cosmos-1_0-Diffusion-7B-Text2World.safetensors"
dir = "models/diffusion_models"
filename = "Cosmos-1_0-Diffusion-7B-Text2World.safetensors"

## 14B
# [[models]]
# url = "https://huggingface.co/mcmonkey/cosmos-1.0/resolve/main/Cosmos-1_0-Diffusion-14B-Video2World.safetensors"
# dir = "models/diffusion_models"
# filename = "Cosmos-1_0-Diffusion-14B-Video2World.safetensors"

# [[models]]
# url = "https://huggingface.co/mcmonkey/cosmos-1.0/resolve/main/Cosmos-1_0-Diffusion-14B-Text2World.safetensors"
# dir = "models/diffusion_models"
# filename = "Cosmos-1_0-Diffusion-14B-Text2World.safetensors"