# t2v
## 14B
# [[models]]
# url = "https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/diffusion_models/wan2.1_t2v_14B_fp16.safetensors"
# dir = "models/diffusion_models/wan21"
# filename = "wan2.1_t2v_14B_fp16.safetensors"

[[models]]
url = "https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/diffusion_models/wan2.1_t2v_14B_fp8_scaled.safetensors"
dir = "models/diffusion_models/wan21"
filename = "wan2.1_t2v_14B_fp8_scaled.safetensors"

# 1.3B
[[models]]
url = "https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/diffusion_models/wan2.1_t2v_1.3B_fp16.safetensors"
dir = "models/diffusion_models/wan21"
filename = "wan2.1_t2v_1.3B_fp16.safetensors"
