# text encoder
[[models]]
url = "https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/text_encoders/umt5_xxl_fp16.safetensors"
dir = "models/text_encoders"
filename = "umt5_xxl_fp16.safetensors"

[[models]]
url = "https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/text_encoders/umt5_xxl_fp8_e4m3fn_scaled.safetensors"
dir = "models/text_encoders"
filename = "umt5_xxl_fp8_e4m3fn_scaled.safetensors"

# vae
[[models]]
url = "https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/vae/wan_2.1_vae.safetensors"
dir = "models/vae"
filename = "wan_2.1_vae.safetensors"

# clip vision
[[models]]
url = "https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/clip_vision/clip_vision_h.safetensors"
dir = "models/clip_vision"
filename = "clip_vision_h.safetensors"
